/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cardstackapplication.view;

import javax.swing.JOptionPane;
import javax.swing.JTextField;
import cardstackapplication.logic.DiceRoll;
import java.util.ArrayList;
import java.util.Collections;
import java.util.Iterator;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Random;
import java.util.Set;

/**
 *
 * @author SonOfBatman
 */
public class GUI extends javax.swing.JFrame {
    /**
     * Create a DiceRoll Object So We can Access DiceRoll methods
     */
    DiceRoll dice;
    LinkedHashMap dataStorage = new LinkedHashMap();
    LinkedHashMap drawnStacks = new LinkedHashMap();
    LinkedHashMap cardsRemoved = new LinkedHashMap();
    ArrayList<String> drawnNumbers = new ArrayList<String>();

    /**
     * Creates new form GUI
     */
    public GUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnPrevNumDice = new javax.swing.JButton();
        btnReqRoll = new javax.swing.JButton();
        btnPeek = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        screen = new javax.swing.JTextArea();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnPrevNumDice.setText("Previous # of Dice");
        btnPrevNumDice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrevNumDiceActionPerformed(evt);
            }
        });

        btnReqRoll.setText("Request Dice Roll");
        btnReqRoll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReqRollActionPerformed(evt);
            }
        });

        btnPeek.setText("Peek");
        btnPeek.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPeekActionPerformed(evt);
            }
        });

        screen.setEditable(false);
        screen.setBackground(new java.awt.Color(204, 204, 204));
        screen.setColumns(20);
        screen.setLineWrap(true);
        screen.setRows(5);
        screen.setWrapStyleWord(true);
        jScrollPane1.setViewportView(screen);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnPrevNumDice)
                .addGap(79, 79, 79)
                .addComponent(btnReqRoll)
                .addGap(84, 84, 84)
                .addComponent(btnPeek, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(124, 124, 124))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 692, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(59, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 382, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPrevNumDice)
                    .addComponent(btnReqRoll)
                    .addComponent(btnPeek))
                .addContainerGap())
        );

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        jMenu3.setText("Help");
        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPeekActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPeekActionPerformed
        // TODO add your handling code here:
        // TODO Request Dice ROll Functionality
        JTextField stack = new JTextField();
        //JTextField cardsToDeal = new JTextField();
        Object[] message = {
            "Stack:", stack,
        };

        int option = JOptionPane.showConfirmDialog(null, message, "Peek", JOptionPane.OK_CANCEL_OPTION);
        if (option == JOptionPane.OK_OPTION) {
            String diceRolled = stack.getText();
            // Key might be present...
            if (dataStorage.containsKey(diceRolled)) {
                 // Get a set of the entries
                    Set firstPeek = dataStorage.entrySet();

                    // Get an iterator
                    Iterator i = firstPeek.iterator();

                    // Display elements
                    while(i.hasNext()) {
                        Map.Entry me = (Map.Entry)i.next();
                        screen.setText("Next Generated Values: ");
                        String value =  me.getValue().toString();
                        screen.append(value);
                    }
                    // Get a set of the entries
                    ArrayList cardsR = (ArrayList) cardsRemoved.get(diceRolled);
                    if(cardsR.isEmpty()){
                        screen.setText("Empty");
                    }else{screen.append("Cards Removed: "+cardsR.get(0));
                    for(int l=0; l<=cardsR.size(); l++){
                        Object value = cardsR.get(0);
                        screen.append((String) value);
                    }}
                    
                    // Get a set of the entries
                    ArrayList cardsD = (ArrayList) drawnStacks.get(diceRolled);
                    if(cardsD.isEmpty()){
                        screen.setText("Empty");
                    }else{
                    System.out.println(cardsD.get(0));
                    screen.append("Cards Drawn: "+cardsD.get(0));
                    for(int m=0; m<=cardsD.size(); m++){
                        Object value = cardsR.get(0);
                        screen.append((String) value);
                    }
                    }
                    
            } else {
                screen.setText("Stack Doesnt Exist");
            }
        }else{
        }
    }//GEN-LAST:event_btnPeekActionPerformed

    private void btnReqRollActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReqRollActionPerformed
        // TODO Request Dice ROll Functionality
        JTextField numOfDie = new JTextField();
        JTextField numOfFaces = new JTextField();
        JTextField cardsToDeal = new JTextField();
        Object[] message = {
            "Number Of Dice:", numOfDie,
            "Number of Faces:", numOfFaces,
            "Cards To Remove:", cardsToDeal
        };
        int cardsDealt = 0;
        int option = JOptionPane.showConfirmDialog(null, message, "Faces, Die, Cards to Deal", JOptionPane.OK_CANCEL_OPTION);
        if (option == JOptionPane.OK_OPTION) {
            if(cardsToDeal.getText().isEmpty()){
                cardsDealt = 0;
                diceRoll = numOfDie.getText()+"d"+numOfFaces.getText()+"-"+Integer.toString(cardsDealt);
                // Key might be present...
                if (dataStorage.containsKey(diceRoll)) {

                    /*

                    */
                    ArrayList rValues = (ArrayList) dataStorage.get(diceRoll);
                    System.out.println(rValues.get(2));

                } else {
                    // Definitely no such key
                    int numFaces = Integer.parseInt(numOfFaces.getText());
                    int numDice = Integer.parseInt(numOfDie.getText());
                    int dice;
                    ArrayList num_freq = new ArrayList();
                    ArrayList<Integer> distribution = new ArrayList<Integer>();
                    Random rand = new Random();
                    int summation = 0;
                    for ( int roll1 = 1; roll1 <=10000; roll1++ ) {
                        int total = 0;
                        for(int j = 0; j<= numDice; j++){
                            dice =  rand.nextInt(40)+ 2;
                            summation = total+dice;
                        }
                        distribution.add(summation);
                    }
                    for (int i = 0; i <= distribution.size(); i++){
                        num_freq.add(Collections.frequency(distribution, i));
                    }
                    dataStorage.put(diceRoll,num_freq);
                    // Get a set of the entries
                    Set set = dataStorage.entrySet();

                    // Get an iterator
                    Iterator i = set.iterator();

                    // Display elements
                    while(i.hasNext()) {
                        Map.Entry me = (Map.Entry)i.next();
                        System.out.print(me.getKey() + ": ");
                        System.out.println(me.getValue());
                    }
                    int numberofitems = num_freq.size();
                    System.out.println(numberofitems);
                }
            }else{
                diceRoll = numOfDie.getText()+"d"+numOfFaces.getText()+"-"+cardsToDeal.getText();
                // Key might be present...
                if (dataStorage.containsKey(diceRoll)) {
                    ArrayList rValues = (ArrayList) dataStorage.get(diceRoll);
                    System.out.println(rValues.get(2));

                } else {
                    // Definitely no such key
                    int numFaces = Integer.parseInt(numOfFaces.getText());
                    int numDice = Integer.parseInt(numOfDie.getText());
                    int numcardsRemoved = Integer.parseInt(cardsToDeal.getText());
                    int dice;
                    LinkedHashMap num_freq = new LinkedHashMap();
                    ArrayList<Integer> distribution = new ArrayList<Integer>();
                    Random rand = new Random();
                    int summation = 0;
                    for ( int roll1 = 1; roll1 <=10000; roll1++ ) {
                        int total = 0;
                        for(int j = 0; j<= numDice; j++){
                            dice =  rand.nextInt(40)+ 2;
                            summation = total+dice;
                        }
                        distribution.add(summation);
                    }
                    //Shuffle the distribution
                    Collections.shuffle(distribution);
                    
                    ArrayList<Integer> cards = new ArrayList<Integer>();
                    for(int i=1; i<=numcardsRemoved; i++){
                        int value = distribution.get(i);
                        distribution.remove(i);
                        cards.add(value);
                        
                    }
                    cardsRemoved.put(diceRoll, cards);
                    for (int i = 0; i <= distribution.size(); i++){
                        num_freq.put(i, Collections.frequency(distribution, i));
                    }
                    dataStorage.put(diceRoll,num_freq);
                    // Get a set of the entries
                    Set set = dataStorage.entrySet();

                    // Get an iterator
                    Iterator i = set.iterator();

                    // Display elements
                    while(i.hasNext()) {
                        Map.Entry me = (Map.Entry)i.next();
                        System.out.print(me.getKey() + ": ");
                        System.out.println(me.getValue());
                    }
                    int numberofitems = num_freq.size();
                    System.out.println(numberofitems);
                }
            }
        } else {
            System.out.println("Deal later");

        }

    }//GEN-LAST:event_btnReqRollActionPerformed

    /**************************************************************************************************************
    Previous Number of dice requested => Deal off the stack and store in a list of drawn numbers
    ***************************************************************************************************************
    */
    private void btnPrevNumDiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrevNumDiceActionPerformed
        //Get the last dice combination
        //Get the number of Dice
        //Draw a number from the Stack and Store it

        String out = null;
        Object key = null;
        LinkedHashMap last = null;
        for (Iterator it = dataStorage.keySet().iterator(); it.hasNext();) {
            key = it.next();
            last = (LinkedHashMap) dataStorage.get(key);
            //String numberDie = (String) key;
            String test = (String) last.get(key);
            drawnNumbers.add(test);
            cardsRemoved.put(key, drawnNumbers);
            last.remove(test);
        }
        /*
        Slice the String, Get the the number of dice from the notation <num>d<faces>-<cards dealt>
        */
        String numberDice = (String) key;
        char arr[]=numberDice.toCharArray();
        screen.setText("Number of Dice: "+arr[0]);
    }//GEN-LAST:event_btnPrevNumDiceActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI().setVisible(true);
            }
        });
    }
    
    //Declaration of Variables
    private String diceRoll;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPeek;
    private javax.swing.JButton btnPrevNumDice;
    private javax.swing.JButton btnReqRoll;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea screen;
    // End of variables declaration//GEN-END:variables
}
