/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cardstackapplication.view;

import javax.swing.JOptionPane;
import javax.swing.JTextField;
import cardstackapplication.logic.DiceRoll;
import java.util.ArrayList;
import java.util.Collections;
import java.util.HashMap;
import java.util.HashSet;
import java.util.Iterator;
import java.util.Map;
import java.util.Random;
import java.util.Set;

/**
 *
 * @author SonOfBatman
 */
public class GUI extends javax.swing.JFrame {
    /**
     * Create a DiceRoll Object So We can Access DiceRoll methods
     */
    DiceRoll dice;
    HashMap dataStorage = new HashMap();

    /**
     * Creates new form GUI
     */
    public GUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnPrevNumDice = new javax.swing.JButton();
        btnReqRoll = new javax.swing.JButton();
        btnPeek = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnPrevNumDice.setText("Previous # of Dice");
        btnPrevNumDice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrevNumDiceActionPerformed(evt);
            }
        });

        btnReqRoll.setText("Request Dice Roll");
        btnReqRoll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReqRollActionPerformed(evt);
            }
        });

        btnPeek.setText("Peek");
        btnPeek.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPeekActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 726, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 395, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(136, 136, 136)
                .addComponent(btnPrevNumDice)
                .addGap(28, 28, 28)
                .addComponent(btnReqRoll)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnPeek)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(35, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPrevNumDice)
                    .addComponent(btnReqRoll)
                    .addComponent(btnPeek))
                .addContainerGap())
        );

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        jMenu3.setText("Help");
        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPrevNumDiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrevNumDiceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPrevNumDiceActionPerformed

    private void btnReqRollActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReqRollActionPerformed
        // TODO Request Dice ROll Functionality
        JTextField numOfDie = new JTextField();
        JTextField numOfFaces = new JTextField();
        //JTextField cardsToDeal = new JTextField();
        Object[] message = {
            "Number Of Dice:", numOfDie,
            "Number of Faces:", numOfFaces,
           // "Cards To Deal:", cardsToDeal
        };

        int option = JOptionPane.showConfirmDialog(null, message, "Faces, Die, Cards to Deal", JOptionPane.OK_CANCEL_OPTION);
        if (option == JOptionPane.OK_OPTION) {
            diceRoll = numOfDie.getText()+"d"+numOfFaces.getText();
            // Key might be present...
            if (dataStorage.containsKey(diceRoll)) {
               System.out.println("I exist, wanna see my distribution");
            } else {
               // Definitely no such key
               int numFaces = Integer.parseInt(numOfFaces.getText());
            int numDice = Integer.parseInt(numOfDie.getText());
            //int cardsDealt = Integer.parseInt(cardsToDeal.getText());
            //dice.rollDice(numDice, numFaces);
            int dice; 
            Random rand = new Random(); 
            final int arraysize = 13;
            double percentage = 0;
            ArrayList<Integer> distribution = new ArrayList<Integer>();
            HashMap num_freq = new HashMap();
            int summation = 0;
            for ( int roll1 = 1; roll1 <=10000; roll1++ ) {
                int total = 0; 
                for(int j = 0; j<= numDice; j++){
                    dice =  rand.nextInt(20)+ 2;
                    summation = total+dice;
                }
                distribution.add(summation);
            }
                for (int i = 0; i <= distribution.size(); i++){
                    num_freq.put(i, Collections.frequency(distribution, i));
                }
                dataStorage.put(diceRoll,num_freq);
                double percentages;
                percentages = Collections.frequency(distribution, 6);
                Double calcPercentage = (percentages/10000)*100;
            // Get a set of the entries
                Set set = dataStorage.entrySet();

                // Get an iterator
                Iterator i = set.iterator();

                // Display elements
                while(i.hasNext()) {
                   Map.Entry me = (Map.Entry)i.next();
                   System.out.print(me.getKey() + ": ");
                   System.out.println(me.getValue());
                }
                int numberofitems = num_freq.size();
                System.out.println(numberofitems);
            }
        } else {
            System.out.println("Deal later");
        }
        

    }//GEN-LAST:event_btnReqRollActionPerformed

    private void btnPeekActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPeekActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPeekActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI().setVisible(true);
            }
        });
    }
    
    //Declaration of Variables
    private String diceRoll;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPeek;
    private javax.swing.JButton btnPrevNumDice;
    private javax.swing.JButton btnReqRoll;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
